# Build all images and run all containers
# `docker-compose -f docker-compose.yml build`

version: '3.7'

services:
  app:
   image: registry.lts.harvard.edu/lts/hdc:7.7.0-lts-2
   build:
     context: .
     dockerfile: Dockerfile

