version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - solr
    ports:
      - "3000:3000"
    environment:
      SOLR_URL: "http://solr:8983/solr/blacklight-core"
      DEVELOPMENT_ENVIRONMENT: "docker"
    entrypoint:
      - /app/bin/start.sh

  solr:
    image: solr:7
    volumes:
      - $PWD/lib/generators/blacklight/templates/solr/conf:/opt/solr/conf
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
