default: &default
  adapter: mysql2
  user: hdc
  port: 3306
  database: hdc_dev
  password: hdcinth3pl4c3tob3
  host: localhost
  
development:
  <<: *default

test:
  <<: *default

production: 
  <<: *default
